sources:
  - name: raw
    schema: gw_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: copy  marketing department adwords raw data
      - name: bing
        identifier: raw_gz_bing
        description: copy  marketing department bing raw data  
      - name: criteo
        identifier: raw_gz_criteo
        description: copy  marketing department criteo raw data  
      - name: facebook
        identifier: raw_gz_facebook
        description: copy  marketing department facebook raw data                       
              

      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez

        ## freshness testing
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: {count: 90, period: day}

        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: products_id
            description: foreign key to product
          - name: revenue
            description: amt paid by customer
          - name: quantity
            description: quantity  of purchase
        
        

      - name: product
        identifier: raw_gz_product
        description: product data for greenwez
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
                  
          - name: purchase_price
            description:  purchase


      - name: ship
        identifier: raw_gz_ship
        description: shipping data for greenwex
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
              
          - name: shipping_fee
            description: shipping free 
          - name: log_cost
            description: cost of preparing parcel
          - name: ship_cost
            description: cost of shipping

models:
  - name: int_sales_margin
    description: margin calculation per order
    columns:
      - name: orders_id
        description: primary key
        tests:
        
          - not_null
      - name: products_id
        description: products key
        tests:
          - not_null
      - name: margin
        description: margin = reve - purchase cost
        tests:
          - not_null
      - name: purchase_cost
        description: purchase cost
        tests:
          - not_null
      - name: date_date
        description: order date
        tests:
          - not_null
      - name: revenue
        description: sum of revenue
        tests:
          - not_null
      - name: quantity
        description: sum of quantity
        tests:
          - not_null

  